# Generated by Django 4.2.4 on 2023-08-15 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя, отчество')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.roles', verbose_name='Роль')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.users', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Структура',
                'verbose_name_plural': 'Структуры',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.structures', verbose_name='Структура')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.structures', verbose_name='Структура')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
