# Generated by Django 4.2.4 on 2023-11-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_reports_nds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('sum', models.FloatField(verbose_name='Сумма заказа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail клиента')),
                ('phone', models.PositiveSmallIntegerField(verbose_name='Телефон клиента')),
                ('date_of_receiving', models.DateTimeField(verbose_name='Желаемая дата получения заказа')),
                ('comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('file', models.FileField(upload_to='uploads/ordersIBC/%Y/%m/%d/', verbose_name='Файл')),
                ('status', models.CharField(max_length=15, verbose_name='Статус заказа')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
