# Generated by Django 4.2.4 on 2023-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.PositiveIntegerField(verbose_name='Телефон клиента'),
        ),
    ]
