# Generated by Django 4.2.4 on 2023-12-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_of_receiving',
            field=models.DateTimeField(blank=True, verbose_name='Желаемая дата получения заказа'),
        ),
    ]
